# AUTO-GENERATED by manage_agents.py — do not edit manually

AGENT_REGISTRY: dict[str, list[str]] = {
    'pageagent-extractor': ['deepaktm-pageagent-extractor', 'deepaktm-pageagent-extractor-copy1', 'deepaktm-pageagent-extractor-copy2', 'deepaktm-pageagent-extractor-copy3', 'deepaktm-pageagent-extractor-copy4', 'deepaktm-pageagent-extractor-copy5', 'deepaktm-pageagent-extractor-copy6'],
    'pageagent-reconciler': ['deepaktm-pageagent-reconciler', 'deepaktm-pageagent-reconciler-copy1', 'deepaktm-pageagent-reconciler-copy2', 'deepaktm-pageagent-reconciler-copy3', 'deepaktm-pageagent-reconciler-copy4', 'deepaktm-pageagent-reconciler-copy5', 'deepaktm-pageagent-reconciler-copy6'],
    'pageagent-validator': ['deepaktm-pageagent-validator', 'deepaktm-pageagent-validator-copy1', 'deepaktm-pageagent-validator-copy2', 'deepaktm-pageagent-validator-copy3', 'deepaktm-pageagent-validator-copy4', 'deepaktm-pageagent-validator-copy5', 'deepaktm-pageagent-validator-copy6'],
    'pageagent-fallback-best-effort-selector': ['deepaktm-pageagent-fallback-best-effort-selector', 'deepaktm-pageagent-fallback-best-effort-selector-copy1', 'deepaktm-pageagent-fallback-best-effort-selector-copy2', 'deepaktm-pageagent-fallback-best-effort-selector-copy3', 'deepaktm-pageagent-fallback-best-effort-selector-copy4', 'deepaktm-pageagent-fallback-best-effort-selector-copy5', 'deepaktm-pageagent-fallback-best-effort-selector-copy6'],
    'masteragent-pdf-quality-validator': ['deepaktm-masteragent-pdf-quality-validator', 'deepaktm-masteragent-pdf-quality-validator-copy1', 'deepaktm-masteragent-pdf-quality-validator-copy2'],
    'masteragent-synopsis-from-toc': ['deepaktm-masteragent-synopsis-from-toc', 'deepaktm-masteragent-synopsis-from-toc-copy1', 'deepaktm-masteragent-synopsis-from-toc-copy2'],
    'masteragent-synopsis-check': ['deepaktm-masteragent-synopsis-check', 'deepaktm-masteragent-synopsis-check-copy1', 'deepaktm-masteragent-synopsis-check-copy2'],
    'masteragent-sections-from-toc': ['deepaktm-masteragent-sections-from-toc', 'deepaktm-masteragent-sections-from-toc-copy1', 'deepaktm-masteragent-sections-from-toc-copy2'],
    'cropagent-propose-bbox': ['deepaktm-cropagent-propose-bbox', 'deepaktm-cropagent-propose-bbox-copy1', 'deepaktm-cropagent-propose-bbox-copy2'],
    'cropagent-validate-bbox': ['deepaktm-cropagent-validate-bbox', 'deepaktm-cropagent-validate-bbox-copy1', 'deepaktm-cropagent-validate-bbox-copy2'],
}
